#version: '3.8'
#
#services:
#  mysql:
#    image: mysql:8.0
#    container_name: mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: raksa12534
#      MYSQL_DATABASE: attendance_system
#    ports:
#      - "3306:3306"  # host:container
#    volumes:
#      - mysql-data:/var/lib/mysql
#
#  backend:
#    build:
#      context: ./backend
#    container_name: node-backend
#    restart: always
#    ports:
#      - "3001:3001"
#    depends_on:
#      - mysql
#    environment:
#      DB_HOST: mysql
#      DB_PORT: 3307
#      DB_USER: root
#      DB_PASSWORD: raksa12534
#      DB_NAME: attendance_system
#
#volumes:
#  mysql-data:






version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: raksa12534
      MYSQL_DATABASE: attendance_system
    ports:
      - "3308:3306"  # Change this to avoid port conflict

  backend:
    build:
      context: ./backend
    container_name: node-backend
    ports:
      - "3001:3001"
    depends_on:
      - mysql

